// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOfvq4cpzjM8vg8FgfWbTSWJtlgrLlMCY',
    appId: '1:491633052627:web:4730e058e4b828413e3d26',
    messagingSenderId: '491633052627',
    projectId: 'todolist-firebase-e3864',
    authDomain: 'todolist-firebase-e3864.firebaseapp.com',
    storageBucket: 'todolist-firebase-e3864.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQPg4JxVdI7usY0UWkrgRsOFNpJ5brCc',
    appId: '1:491633052627:android:cd4164229c56ed183e3d26',
    messagingSenderId: '491633052627',
    projectId: 'todolist-firebase-e3864',
    storageBucket: 'todolist-firebase-e3864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSAIUelu3KQVwT9x_OYXJUmHVBxAmExtw',
    appId: '1:491633052627:ios:49e398e56c9dbe223e3d26',
    messagingSenderId: '491633052627',
    projectId: 'todolist-firebase-e3864',
    storageBucket: 'todolist-firebase-e3864.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSAIUelu3KQVwT9x_OYXJUmHVBxAmExtw',
    appId: '1:491633052627:ios:49e398e56c9dbe223e3d26',
    messagingSenderId: '491633052627',
    projectId: 'todolist-firebase-e3864',
    storageBucket: 'todolist-firebase-e3864.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOfvq4cpzjM8vg8FgfWbTSWJtlgrLlMCY',
    appId: '1:491633052627:web:5e318f94025e8f2b3e3d26',
    messagingSenderId: '491633052627',
    projectId: 'todolist-firebase-e3864',
    authDomain: 'todolist-firebase-e3864.firebaseapp.com',
    storageBucket: 'todolist-firebase-e3864.appspot.com',
  );
}
